# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canonyze < Formula
  desc "Canonizes a set of yaml documents into a standardized and sorted form that is suitable for comparison against another set"
  homepage "https://github.com/nestoca/canonyze"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/canonyze/releases/download/v0.2.0/canonyze_0.2.0_darwin_arm64.tar.gz"
      sha256 "27bada8597e1e5036493c8fecc76374eb5c10b15a6be3392b1b0628ea4241b36"

      def install
        bin.install "canonyze"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/canonyze/releases/download/v0.2.0/canonyze_0.2.0_darwin_x86_64.tar.gz"
      sha256 "c080c56b87c4889bad7ca2bbcff204ce834d445eb0349e799a0baf0b7aae23a8"

      def install
        bin.install "canonyze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/canonyze/releases/download/v0.2.0/canonyze_0.2.0_linux_arm64.tar.gz"
      sha256 "c2a30af0d877ab4b1cc79874fe9b0ee9142a252c3ea5ed4cfea86aad6351a9e4"

      def install
        bin.install "canonyze"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/canonyze/releases/download/v0.2.0/canonyze_0.2.0_linux_x86_64.tar.gz"
      sha256 "a1a06854ba085f155e1864992981e98ad402eb188df952372bdfb38ff68e75c9"

      def install
        bin.install "canonyze"
      end
    end
  end
end
