# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canonyze < Formula
  desc "Canonizes a set of yaml documents into a standardized and sorted form that is suitable for comparison against another set"
  homepage "https://github.com/nestoca/canonyze"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/canonyze/releases/download/v0.1.0/canonyze_0.1.0_darwin_arm64.tar.gz"
      sha256 "6d11551af054b7bbcda059a7328cf25370a369ec220f60361d3c8274f9005b5b"

      def install
        bin.install "canonyze"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/canonyze/releases/download/v0.1.0/canonyze_0.1.0_darwin_x86_64.tar.gz"
      sha256 "38ffc58ee722d0c7980586c2f60d4b6c439adaf7ae290527c315662158dc660e"

      def install
        bin.install "canonyze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/canonyze/releases/download/v0.1.0/canonyze_0.1.0_linux_arm64.tar.gz"
      sha256 "ef167cca5e70599ef026b1886ad438b524f6b2289d5332b2d7b4d6c5f61f2cec"

      def install
        bin.install "canonyze"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/canonyze/releases/download/v0.1.0/canonyze_0.1.0_linux_x86_64.tar.gz"
      sha256 "7c162981e6d80eefbe3bc2da1acab4b937c2f2e6ce92ff9fd08c018e1c01f68e"

      def install
        bin.install "canonyze"
      end
    end
  end
end
