# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamlcanonizer < Formula
  desc "Canonizes a set of yaml documents into a standardized and sorted form that is suitable for comparison against another set"
  homepage "https://github.com/nestoca/yamlcanonizer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nestoca/yamlcanonizer/releases/download/v0.1.0/yamlcanonizer_0.1.0_darwin_arm64.tar.gz"
      sha256 "a3df274a0d80676fd0d5492cffec3be499f1fff69b677cdccdc6c95daaf65dfc"

      def install
        bin.install "yamlcanonizer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/yamlcanonizer/releases/download/v0.1.0/yamlcanonizer_0.1.0_darwin_x86_64.tar.gz"
      sha256 "e9588b859d184dc320e081b8268cbc9d535c747e0101dc573987466ddae4df0e"

      def install
        bin.install "yamlcanonizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nestoca/yamlcanonizer/releases/download/v0.1.0/yamlcanonizer_0.1.0_linux_arm64.tar.gz"
      sha256 "14b04422156fa04d836e2856a286a70a5a8465cfa6e0159473b06cbe527e5c9d"

      def install
        bin.install "yamlcanonizer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nestoca/yamlcanonizer/releases/download/v0.1.0/yamlcanonizer_0.1.0_linux_x86_64.tar.gz"
      sha256 "810bebbbc623588d6ba657b76d5d5771762280e9d840c5fb8275b8683e1863bc"

      def install
        bin.install "yamlcanonizer"
      end
    end
  end
end
